server:
  port: 9569
spring:
  application:
    name: redispractice #指定服务名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myhub?serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: false
    generate-ddl: false
    open-in-view: false
    hibernate: #设置JPA对数据库字段下划线的转译
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  redis:
    host: 127.0.0.1       # Redis服务器地址
    database: 1           # Redis数据库索引（默认为0）
    port: 6379            # Redis服务器连接端口
    password:             # Redis服务器连接密码（默认为空）
    timeout: 1000ms       # 连接超时时间
    lettuce:
      pool:
        max-active: 8       # 连接池最大连接数
        max-idle: 8         # 连接池最大空闲连接数
        min-idle: 0         # 连接池最小空闲连接数
        max-wait: -1ms      # 连接池最大阻塞等待时间，负值表示没有限制