spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myhub?serverTimezone=UTC #&allowMultiQueries=true#支持多重查询
    username: root
    password: 123456
  redis:
    host: 127.0.0.1       # Redis服务器地址
    database: 2           # Redis数据库索引（默认为0）
    port: 6379            # Redis服务器连接端口
    password:             # Redis服务器连接密码（默认为空）
    timeout: 1000ms       # 连接超时时间
    lettuce:
      pool:
        max-active: 8       # 连接池最大连接数
        max-idle: 8         # 连接池最大空闲连接数
        min-idle: 0         # 连接池最小空闲连接数
        max-wait: -1ms      # 连接池最大阻塞等待时间，负值表示没有限制
mybatis:              #mytis配置
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.itcodes.myhub.redistemplatepractice.pojo